name: flutter_otp_widget
description: A highly customizable OTP (One-Time Password) text field widget for Flutter with support for multiple styles, themes, and input types.
version: 1.0.1
homepage: https://github.com/kihyun1998/flutter_otp_widget
repository: https://github.com/kihyun1998/flutter_otp_widget
issue_tracker: https://github.com/kihyun1998/flutter_otp_widget/issues
documentation: https://pub.dev/documentation/flutter_otp_widget/latest/

topics:
  - otp
  - textfield
  - pin
  - verification
  - authentication

screenshots:
  - description: "Box style OTP field"
    path: screenshot/box_exampel.png
  - description: "Underline style OTP field"
    path: screenshot/underline_example.png
  - description: "Circle style OTP field"
    path: screenshot/circle_example.png
  - description: "Secure PIN entry with obscured text"
    path: screenshot/secure_example.png
  - description: "Error state styling"
    path: screenshot/error_example.png

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # This package has no assets
